name: hu-neuro-pipeline-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - jupytext
  - nbsphinx
  - r-base
  - r-dplyr
  - r-ggplot2
  - r-irkernel
  - r-lme4
  - r-reticulate
  - r-rmisc
  - sphinx-book-theme
  - sphinx-copybutton
  - sphinx-gallery
